apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: hotel-app
data:
  init.sql: |
    -- Create Users Table
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(100) NOT NULL UNIQUE,
      email VARCHAR(100) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      first_name VARCHAR(100),
      last_name VARCHAR(100),
      phone VARCHAR(20),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    -- Create Rooms Table
    CREATE TABLE IF NOT EXISTS rooms (
      id INT AUTO_INCREMENT PRIMARY KEY,
      room_number VARCHAR(50) NOT NULL UNIQUE,
      room_type VARCHAR(50) NOT NULL,
      capacity INT NOT NULL,
      price_per_night DECIMAL(10, 2) NOT NULL,
      description TEXT,
      is_available BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    -- Create Bookings Table
    CREATE TABLE IF NOT EXISTS bookings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      room_id INT NOT NULL,
      check_in_date DATE NOT NULL,
      check_out_date DATE NOT NULL,
      total_price DECIMAL(10, 2) NOT NULL,
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
    );

    -- Create Reviews Table
    CREATE TABLE IF NOT EXISTS reviews (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      room_id INT NOT NULL,
      rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
      comment TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
    );

    -- Insert Sample Rooms
    INSERT INTO rooms (room_number, room_type, capacity, price_per_night, description, is_available) VALUES
    ('101', 'Single', 1, 50.00, 'Cozy single room with city view', TRUE),
    ('102', 'Double', 2, 80.00, 'Comfortable double room', TRUE),
    ('103', 'Suite', 4, 150.00, 'Luxury suite with living area', TRUE),
    ('104', 'Double', 2, 85.00, 'Spacious double room with balcony', TRUE),
    ('105', 'Single', 1, 55.00, 'Modern single room', TRUE);

    -- Create Indexes for Performance
    CREATE INDEX idx_user_email ON users(email);
    CREATE INDEX idx_booking_user ON bookings(user_id);
    CREATE INDEX idx_booking_room ON bookings(room_id);
    CREATE INDEX idx_booking_dates ON bookings(check_in_date, check_out_date);
    CREATE INDEX idx_review_room ON reviews(room_id);
