apiVersion: v1
kind: LimitRange
metadata:
  name: hotel-limits
  namespace: hotel-app
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    type: Container
